apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  namespace: bookretail-istio-system
  name: basic
spec:
  security:
    certificateAuthority:
      istiod:
        type: PrivateKey
      type: Istiod
    dataPlane:
      automtls: false
      mtls: false
  tracing:
    sampling: 10000
    type: Jaeger
  profiles:
    - default
  proxy:
    accessLogging:
      file:
        encoding: TEXT
        name: /dev/stdout
    runtime:
      container:
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      readiness:
        rewriteApplicationProbes: true
  gateways:
    egress:
      runtime:
        deployment:
          autoScaling:
            enabled: false
      service: {}
    ingress:
      runtime:
        deployment:
          autoScaling:
            enabled: false
      service: {}
    openshiftRoute:
      enabled: true
  techPreview:
    kiali:
      dashboard:
        passphrase: redhat
        user: admin
  policy:
    mixer:
      enableChecks: false
  addons:
    3scale:
      enabled: false
    kiali: {}
  version: v2.0
  runtime:
    components:
      mixer.policy:
        deployment:
          autoScaling:
            enabled: false
      mixer.telemetry:
        container:
          resources:
            limits:
              cpu: 500m
              memory: 4G
            requests:
              cpu: 100m
              memory: 1G
        deployment:
          autoScaling:
            enabled: false
      pilot:
        deployment:
          autoScaling:
            enabled: false

